# Generated by Django 5.2.2 on 2025-06-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='unidade_med',
            field=models.CharField(),
        ),
    ]
