# Generated by Django 5.2.2 on 2025-06-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sensor_unidade_med'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='ambiente',
        ),
    ]
