# Generated by Django 5.2.2 on 2025-06-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sensor_ambiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor',
            field=models.CharField(choices=[('temperatura', 'Temperatura'), ('luminosidade', 'Luminosidade'), ('umidade', 'Umidade'), ('contador', 'Contador')]),
        ),
    ]
