# Generated by Django 5.2.2 on 2025-06-13 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sensor_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='ambiente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ambiente'),
            preserve_default=False,
        ),
    ]
